-- Add missing columns to markets table
ALTER TABLE markets ADD COLUMN IF NOT EXISTS yes_subtitle VARCHAR(500);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS no_subtitle VARCHAR(500);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS previous_yes_bid INTEGER;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS previous_yes_ask INTEGER;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS previous_price INTEGER;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS result VARCHAR(20);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS can_close_early BOOLEAN DEFAULT false;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS expiration_value VARCHAR(255);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS settlement_timer_seconds INTEGER;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS settlement_source VARCHAR(255);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS custom_strike VARCHAR(255);
ALTER TABLE markets ADD COLUMN IF NOT EXISTS is_deactivated BOOLEAN DEFAULT false;