spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kalshi_mock
    username: kalshi
    password: kalshi_dev_password
    driver-class-name: org.postgresql.Driver
  
  sql:
    init:
      mode: never  # Schema is initialized by Docker
      
server:
  port: 9090

logging:
  level:
    com.kalshi.mock: DEBUG
    org.springframework.jdbc: DEBUG